"""fisrt

Revision ID: 47cb2a7941b1
Revises: 
Create Date: 2021-11-20 17:14:51.756020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cb2a7941b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('time_expiries', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=8000), nullable=False),
    sa.Column('from_at', sa.String(length=8000), nullable=False),
    sa.Column('to', sa.String(length=8000), nullable=False),
    sa.Column('html', sa.String(length=8000), nullable=False),
    sa.Column('text', sa.String(length=8000), nullable=False),
    sa.Column('textAsHtml', sa.String(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=88), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=150), nullable=False),
    sa.Column('max_thread', sa.Integer(), nullable=True),
    sa.Column('thread', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=88), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_check', sa.Boolean(), nullable=False),
    sa.Column('is_baned', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('type_domain', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('use_prefix', sa.Boolean(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_domains_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_domain'), 'domains', ['domain'], unique=True)
    op.create_table('mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=88), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('time_expiries', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_mails_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mails_mail'), 'mails', ['mail'], unique=True)
    op.create_table('emailfrommails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Integer(), nullable=True),
    sa.Column('mail', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['emails.id'], name='fk_emailfrommails_emails_email_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mail'], ['mails.id'], name='fk_emailfrommails_mails_mail_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailfrommails')
    op.drop_index(op.f('ix_mails_mail'), table_name='mails')
    op.drop_table('mails')
    op.drop_index(op.f('ix_domains_domain'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('emails')
    # ### end Alembic commands ###
